app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

translation:
    resource: "@AxiomaTranslationBundle/Resources/config/routing.yml"
    prefix:   /admin
