stfalcon_tinymce:
   include_jquery: false
   tinymce_jquery: true
   selector: ".tinymce"
   base_url: "/" # this parameter may be included if you need to override the assets_base_urls for your template engine (to override a CDN base url)
   # Get current language from the parameters.ini
   language: %locale%
   # Custom buttons
   tinymce_buttons:
   theme:
       # Advanced theme with almost all enabled plugins
       simple:
            width: 668
            height: 330
            plugins:
                - "advlist autolink lists link image charmap print preview hr anchor pagebreak textcolor"
                - "searchreplace wordcount visualblocks visualchars code fullscreen"
                - "insertdatetime media nonbreaking save table contextmenu directionality emoticons template paste"
            toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image print preview media | forecolor backcolor | example textcolor"
            image_advtab: true
       # BBCode tag compatible theme (see http://www.bbcode.org/reference.php)
       bbcode:
            plugins: ["bbcode, code, link"]
            menubar: false
            toolbar1: "bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code"
